### ISSUE TITLE
An update?

### ISSUE THREAD

**Issue by plowsof** [tipxmr/tipxmr#43]
I see work is continuing here, looking good for 2023! could we get an update for your CCS? it seems the first milestone was completed many moons ago, but you recently encountered some technical difficulties. How's it going? let us know @ https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/174 Thank you!

**Comment by hundehausen** [comment]
Hey @plowsof !

Our CCS update:

We are currently active developing TipXMR, and we are close to our second milestone. It's going all right, and we plan to finish the project later this year.

**Comment by plowsof** [comment]
i missed our 3 year anniversary, apologies. Any updates since the last one? 
also if you have a moment:
- there was a [bounty created](https://bounties.monero.social/posts/138/0-000m-message-and-tip-streamers-and-podcasters-with-monero) to fund a project with a similar goal. it claims tipxmr is "one instance per content creator". This is not true right? tipxmr allows multiple streamers to sign up to the service?
- the readme mentions "pay their dues" : how do streamers pay fees to the tipxmr instance owner? is there a flat fee every month? or a one-off sign up? a % scraped directly from each donation?

**Comment by hundehausen** [comment]
Hey @plowsof !

- TipXMR is one instance for lots of users. TipXMR can be hosted by anyone and on each instance allows multiple streamers to sign up.
- We are still not sure about monetization. We had some ideas, but are also afraid of legal aspects. We even thought about just developing TipXMR and not monetize it at all, or even not running an instance by ourselves. 
- The current state of development is that we are stuck with Websockets in Next.js. It doesn't support them natively, and we have to use a custom server for this, but this hasn't worked out yet.
